// Scoreboard Class
class adder_8bit_scoreboard extends uvm_component;
    `uvm_component_utils(adder_8bit_scoreboard)

    uvm_analysis_imp #(adder_8bit_trans, adder_8bit_scoreboard) monitor_ap;

    function new(string name, uvm_component parent);
        super.new(name, parent);
        monitor_ap = new("monitor_ap", this);
    endfunction

    virtual task write(adder_8bit_trans trans);
        bit [8:0] expected_sum;
        expected_sum = trans.a + trans.b + trans.cin;

        if ((expected_sum[7:0] !== trans.sum) || (expected_sum[8] !== trans.cout)) begin
            `uvm_error("CHECK", $sformatf("Mismatch! Inputs: a=%0d, b=%0d, cin=%0d, Expected: sum=%0d, cout=%0d, Got: sum=%0d, cout=%0d",
                                            trans.a, trans.b, trans.cin, expected_sum[7:0], expected_sum[8], trans.sum, trans.cout))
        end else begin
            `uvm_info("CHECK", "Transaction passed", UVM_LOW)
        end
    endtask
endclass// Generated by LLM
