// transaction.sv generated by LLM
// Accumulator UVM Transaction Class
class accu_transaction extends uvm_sequence_item;
    `uvm_object_utils(accu_transaction)

    rand bit [7:0] data_in;
    rand bit valid_in;
    bit valid_out;
    bit [9:0] data_out;

    function new(string name = "accu_transaction");
        super.new(name);
    endfunction

    // Constraints for valid input transactions
    constraint c_valid_in { valid_in == 1'b1; }
endclass