`include "uvm_macros.svh"
import uvm_pkg::*;

`ifdef Llamat1
    `include "../../_llama3/t1/accu_tb/accu_pkg.sv"
`elsif Llamat2
    `include "../../_llama3/t2/accu_tb/accu_pkg.sv"  
`elsif Llamat3
    `include "../../_llama3/t3/accu_tb/accu_pkg.sv"
`elsif Llamat4
    `include "../../_llama3/t4/accu_tb/accu_pkg.sv"
`elsif Llamat5
    `include "../../_llama3/t5/accu_tb/accu_pkg.sv"
`elsif Geminit1
    `include "../../_gemini/t1/accu_tb/accu_pkg.sv"
`elsif Geminit2
    `include "../../_gemini/t2/accu_tb/accu_pkg.sv"
`elsif Geminit3
    `include "../../_gemini/t3/accu_tb/accu_pkg.sv"
`elsif Geminit4
    `include "../../_gemini/t4/accu_tb/accu_pkg.sv"
`elsif Geminit5
    `include "../../_gemini/t5/accu_tb/accu_pkg.sv"
`elsif GPTt1
    `include "../../_chatgpt4o/t1/accu_tb/accu_pkg.sv"
`elsif GPTt2
    `include "../../_chatgpt4o/t2/accu_tb/accu_pkg.sv"
`elsif GPTt3
    `include "../../_chatgpt4o/t3/accu_tb/accu_pkg.sv"
`elsif GPTt4
    `include "../../_chatgpt4o/t4/accu_tb/accu_pkg.sv"
`elsif GPTt5
    `include "../../_chatgpt4o/t5/accu_tb/accu_pkg.sv"
`endif